' C1 - System Context - of C4 Model
!define GITHUB_PLANTUML_URL
@startuml System Context
' C4 Model components
' https://github.com/plantuml-stdlib/C4-PlantUML
!include <C4/C4_Context>
' Icons
' https://github.com/tupadr3/plantuml-icon-font-sprites/tree/main
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons
!include ICONURL/common.puml

!define DEVICONS2 ICONURL/devicons2
!include DEVICONS2/oauth.puml

!define FONT_AWESOME ICONURL/font-awesome-6
!include FONT_AWESOME/user_gear.puml
!include FONT_AWESOME/user.puml
!include FONT_AWESOME/futbol.puml

' People
Person(coach, "Coach", "Coordinator of team sessions", $sprite="user")
Person(admin, "Admin", "Administrator of whole of whole application", $sprite="user_gear")
Person(parent, "Parent", "Parent of child in team", $sprite="user")

System(coachingSystem, "Coach Session Planning System", $sprite="futbol")
System_Ext(auth0, "Auth0", "Auth0 authorisation service", $sprite="oauth")

' CRUD stands for create, read, update, delete
Rel(coach, coachingSystem, "CRUD sessions, CRUD activities, Manage parent accounts")
Rel_R(admin, coachingSystem, "Manage coach/parent accounts")
Rel_U(parent, coachingSystem, "Views child's session")
Rel_R(coachingSystem, auth0, "Authorises users")

SHOW_LEGEND()

@enduml