name: CD_Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          owner: "athNdev"
          repository: ${{ github.event.repository.name }}
          access-token: ${{ secrets.COACHCRAFT_PLATFORM_CONTENTS_RW }}

      - name: Build SPA
        run: |
          cd ${{ github.event.repository.name }}/web
          npm i
          npm run prod

      - name: Bundle web app for Pages depl
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          BUILD_DIR="$REPO_NAME/pages-build"

          # copy built SPA
          cp -a "$REPO_NAME/web/dist/." "$BUILD_DIR/"

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.event.repository.name }}/pages-build

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
